<?php
declare( strict_types=1 );


namespace tests;

use PHPUnit\Framework\TestCase;

class Test_Add extends TestCase {
	
	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		require __DIR__ . '/../example.php';
	}

	public function test_add_function() {
		$this->assertEquals( 4, add( 2, 2 ) );
	}
}
